### ISSUE TITLE
Issue reading vegdyn with Coupled Model

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#663] opened 2021-01-13 16:21 UTC
I'm making an issue here only because the traceback is in MAPL. Namely, when I try to run MOM6 (c90, default ocean) with GNU you get a crash (focusing on pe 0):
```
 Character Resource Parameter: LANDICE_INTERNAL_RESTART_FILE:landice_internal_rst
 Using parallel NetCDF for file: landice_internal_rst
 Character Resource Parameter: VEGDYN_INTERNAL_RESTART_FILE:vegdyn.data
 NOT using buffer I/O for file: vegdyn.data
pe=00000 FAIL at line=01318    MAPL_IO.F90                              <status=5001>
pe=00000 FAIL at line=00983    MAPL_IO.F90                              <status=5001>
pe=00000 FAIL at line=05685    MAPL_Generic.F90                         <status=5001>
pe=00000 FAIL at line=01633    MAPL_Generic.F90                         <unknown error>
pe=00000 FAIL at line=01848    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=01503    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=01848    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=01503    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=01848    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=01503    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=01848    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=01503    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=01848    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=01503    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=01848    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=00608    MAPL_CapGridComp.F90                     <status=1>
pe=00000 FAIL at line=00901    MAPL_CapGridComp.F90                     <status=1>
pe=00000 FAIL at line=00357    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00214    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00160    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00134    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00032    GEOSgcm.F90                              <status=1>
```
with:
```
LANDInitialize                                1497
SURFACEInitialize                             3294
PHYSICS::Initialize                           1628
AGCMInitialize                                1118
GCMInitialize                                 1204
```
either before or after. (Also see: https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/377)

Now, you *can* run C90 GNU AMIP, and it's happy:
```
 Character Resource Parameter: LANDICE_INTERNAL_RESTART_FILE:landice_internal_rst
 Using parallel NetCDF for file: landice_internal_rst
 Character Resource Parameter: VEGDYN_INTERNAL_RESTART_FILE:vegdyn.data
 NOT using buffer I/O for file: vegdyn.data
 Character Resource Parameter: CATCH_INTERNAL_RESTART_FILE:catch_internal_rst
 Using parallel NetCDF for file: catch_internal_rst
```
The line above seems to refer to this code about `IOSTAT_END`:
https://github.com/GEOS-ESM/MAPL/blob/8e933d8adf111af0d4215ecf09c7e0dbe1388ff9/base/MAPL_IO.F90#L1315-L1318

So...not sure. I can say that for MOM6 we use a vegdyn from the coupled initial conditions from @yvikhlya , but then again, this same file is used for Intel MOM6 runs as well...and Intel seems happy. 🤷🏼‍♂️ Maybe, somehow, GNU thinks the file should be a different length?

I tried looking and it looks like both files end in `9c 5a 06 00`. Not sure if that's the hex for a Fortran EOF or not.

**Comment by yvikhlya** [comment] 2021-01-13 16:29
How MOM5 behaves with GNU? I think coupled runs with MOM6/MOM5 use same land restarts.

**Comment by mathomp4** [comment] 2021-01-13 16:39
I guess @sanAkel has infected me with the "MOM6 is the future" bug. I forget about MOM5...

Just did a C90 MOM5 run and it crashes the same way.

**Comment by yvikhlya** [comment] 2021-01-13 16:49
> I guess @sanAkel has infected me with the "MOM6 is the future" bug. I forget about MOM5...
> 
> Just did a C90 MOM5 run and it crashes the same way.

Which is good. We know that the problem is unrelated to ocean model now. What was the last tag which worked with GNU compiler? It worked at some point right? I can guarantee, that land restarts did not changed since then.

**Comment by mathomp4** [comment] 2021-01-13 17:13
@yvikhlya I'm not sure MOM ever worked under GNU? Maybe it did at one point? My nightly testing for MOM5/6 is only with Intel because I didn't want to add more C90 tests.

I only really tried it this time because I wanted to see if the DSO branch on GEOSgcm_GridComp worked with GNU as well as Intel (DSO's are always twitchy). But this crash obviates that test for now. (And the Intel doesn't work for me either.)

**Comment by sanAkel** [comment] 2021-01-13 17:17
1. @mathomp4 indeed MOM6 is the **future**! 😄 
2. We seem to have confirmed that something isn't correct with the modifications proposed in https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/377 (though unrelated to _this_ issue)

**Comment by yvikhlya** [comment] 2021-01-13 17:31
> We seem to have confirmed that something isn't correct with the modifications proposed in GEOS-ESM/GEOSgcm_GridComp#377 (though unrelated to this issue

Not sure about that. The issue could be introduced by some earlier modifications.

**Comment by sanAkel** [comment] 2021-01-14 01:13
Regardless of when and how it was introduced, _here_ we are and it is broken! Of course, fixing it with one ocean model (e.g., MOM5) would most probably fix for the other (e.g., MOM6). Given that the **future** can only be _realized_ if we work towards it, so let's fix it for MOM6.

1. How was the `vegdyn.data` generated? For starters, I don't even understand why it should be different for what stock AMIP uses. It is a file for land, as fas as I understand!
2. I am sure this is a binary file 😞 
  - in which case some fortran compiler was used to generated it, right? 
  - which one was it? 
  - How was the code compiled? 
  - instructions?
3. Is the `vegdyn.data` really to be blamed? Is there way we can be _sure_ about this? Can be skip reading it and see where it dies next?? Something like that...?

**Comment by smahanam** [comment] 2021-01-14 11:41
Could you please point me to the BCSDIR of your experiment?
At some point, we changed  the  file format of vegdyn to nc4. But I am sure MAPL can autodetect the format.
We added 2 new fields to the file few years ago, if your BCs are from pre-Icarus era, GEOSvegdyn would crash.
So please point me to your EXPDIR or BCSDIR, I'll check.

**Comment by sanAkel** [comment] 2021-01-14 12:59
> Could you please point me to the BCSDIR of your experiment?
> At some point, we changed the file format of vegdyn to nc4. But I am sure MAPL can autodetect the format.
> We added 2 new fields to the file few years ago, if your BCs are from pre-Icarus era, GEOSvegdyn would crash.
> So please point me to your EXPDIR or BCSDIR, I'll check.

@yvikhlya would know best!

**Comment by mathomp4** [comment] 2021-01-14 13:10
@smahanam Here is what my runs are pointing to:
```
/discover/nobackup/yvikhlia/coupled/Forcings/MOM6/CF0090x6C_TM0360xTM0210/
```

**Comment by smahanam** [comment] 2021-01-14 13:19
Thanks Matt !
This experiment uses Ganymed-4_0 BCs.
Since Ganymed-4_0 and Icarus land tiles are the same, we can just replace the Ganymed-4_0 vegdyn file with the below Icarus vegdyn file.
/discover/nobackup/ltakacs/bcs/Icarus/Icarus_MERRA-2/CF0090x6C_DE1440xPE0720/vegdyn_90x540.dat

**Comment by sanAkel** [comment] 2021-01-14 13:25
Thank you @mathomp4 , 

@smahanam any reason why these files should be **different** for uncoupled (atmosphere-only; AMIP) and coupled model runs? Also are the land tiles same between Icarus and Jason? @mathomp4 is of course running a Jason (from _this_ repo!). Thanks a lot!

**Comment by smahanam** [comment] 2021-01-14 13:46
Land tiles depend only on the atmospheric grid resolution. 
All ocean grid resolutions under the same atmospheric grid use the same land tiles for e.g.: Reynolds (AMIP), MERRA-2 (AMIP), Ostia (AMIP), MOM  coupled to CF90 atmosphere, will use CF90 land tiles.

Yuri has copied from Larry's BCs directory. When we added the 2 new fields, we updated vegdyn files in the Icarus BCs directory. Sorry, we just have forgotten Yuri's copy.

**Comment by atrayano** [comment] 2021-01-14 13:49
@smahanam Technically, the the land tiles (and all the tiles in general) depend also on the resolution of the raster (i.e. pixel) grid. In the very old system, this used to be 8640x4320. And with increase of the resolution of the grids, we typically bump up the raster resolution (but not always)

**Comment by mathomp4** [comment] 2021-01-14 14:11
As a test, I decided to copy over @yvikhlya's directory to my nobackup and then copied in the C90 `vegdyn.data` from Larry's BCs into that directory and fixed up `gcm_run.j` to run it. And, it seems to work:
```
/gpfsm/dnb02/mathomp4/Experiments/stock-gcm-2021Jan13-1day-c90-MOM6-GNU/1day.with_larry_vegdyn.out
```
Not sure about the output, but it doesn't crash!

**Comment by smahanam** [comment] 2021-01-14 14:35
> @smahanam Technically, the the land tiles (and all the tiles in general) depend also on the resolution of the raster (i.e. pixel) grid. In the very old system, this used to be 8640x4320. And with increase of the resolution of the grids, we typically bump up the raster resolution (but not always)

Yes @atrayano ! land tiles depend on both the land mask (catchment mask) and the atmospheric grid. Yuri's experiments use old mask based BCs with the raster resolution of 8640x4320 - so the vegdyn file that I pointed from Larry has the same number of tiles (104,103).

NL BCs series uses a finer catchment mask and a raster resolution (43200x21600) - so Icarus-NL/CF90 has more tiles than Icarus/CF90

Also, this vegdyn files have own differences within the NL series too. The second field Z2CH differs in NLv2. 
Just some background ....

**Comment by sanAkel** [comment] 2021-01-14 14:36
@mathomp4 Is this plot a **diff** between ...? if so, it would make sense!

Just to be clear, you just replaced whatever @yvikhlya had with those from Larry?

**Comment by yvikhlya** [comment] 2021-01-14 15:19
vegdyn.data in 1 degree resolution is the same as was used to be in AMIP set up. I had no idea that it changed.

**Comment by mathomp4** [comment] 2021-01-14 16:18
> @mathomp4
> 
> 1. Is this plot a **diff** between ...? if so, it would make sense!

Diff between Intel MOM6 and GNU MOM6 of `BULK_SST`

> 2. Just to be clear, you just replaced whatever @yvikhlya had with those from Larry?

Yes, though I was stupid about it. I copied over the `vegdyn_90x540.dat` but didn't copy it *into* `vegdyn.data` so I had to fix bits of `gcm_run.j` to make the link correctly. Probably the better thing is to just copy that file *over* `vegdyn.data` then the `gcm_run.j` needs less fiddling.

> 3. Is this with the GNU? The **error** that you had disappeared? 👻

Yes. It's GNU. And it seemed to run!

**Comment by sanAkel** [comment] 2021-01-14 19:07
> > @mathomp4
> > 

> 
> > 1. Just to be clear, you just replaced whatever @yvikhlya had with those from Larry?
> 
> Yes, though I was stupid about it. I copied over the `vegdyn_90x540.dat` but didn't copy it _into_ `vegdyn.data` so I had to fix bits of `gcm_run.j` to make the link correctly. Probably the better thing is to just copy that file _over_ `vegdyn.data` then the `gcm_run.j` needs less fiddling.
> 
> > 1. Is this with the GNU? The **error** that you had disappeared? 👻
> 
> Yes. It's GNU. And it seemed to run!

Thank you @mathomp4 and also @smahanam 

I guess for now we can settle for 
> > 1. Is this plot a **diff** between ...? if so, it would make sense!
> 
> Diff between Intel MOM6 and GNU MOM6 of `BULK_SST`
that difference.

I would suggest @yvikhlya update the files as suggested by @smahanam and when he does that, this problem will be fixed for GNU and there will be a non-zero diff answer for INTEL too. 

@yvikhlya would you please put in a PR linking this issue? Thanks!

**Comment by yvikhlya** [comment] 2021-01-14 19:17
Right now we are using different versions of coupled model (s2sv2, s3sv3 and jason) with several different resolution. I would argue that we need to manage boundary conditions a little bit more transparent way than we do now. I am always confused which BCs should be used for which version of the model. @sanAkel what PR are you talking about?

**Comment by sanAkel** [comment] 2021-01-14 19:29
@yvikhlya 
>different versions of coupled model (s2sv2, s3sv3 and jason) with several different resolutions.

Both S2S v2 and V3 are residing in **CVS** repository; they don't reside **here** in github. So what you have in 
https://github.com/GEOS-ESM/GEOSgcm_App/blob/ee1397d9a0a25a64ef244ce90179f2a0059c7ad4/gcm_run.j#L340-L361
has absolutely nothing to do with S2S v2 and v3. Once you change
https://github.com/GEOS-ESM/GEOSgcm_App/blob/ee1397d9a0a25a64ef244ce90179f2a0059c7ad4/gcm_run.j#L409 to point to some other `vegdyn.data` then it will impact only Jason version of the model.

>I am always confused which BCs should be used for which version of the model.

You may have whatever files in your path! Only these scripts in https://github.com/GEOS-ESM/GEOSgcm_App have to be updated.

> @sanAkel what PR are you talking about?

That update is what I am anticipating in a PR

**Comment by sanAkel** [comment] 2021-02-08 03:53
Is this issue _resolved_? 

Paging @yvikhlya @mathomp4

**Comment by yvikhlya** [comment] 2021-02-08 14:39
I think the best would be to point land BCs in coupled set up to be the same as in AMIP set up. I'll do the PR in GEOSgcm_App.

**Comment by sanAkel** [comment] 2021-02-08 19:03
👍 looking forward to it

**Comment by sanAkel** [comment] 2021-02-16 21:11
https://github.com/GEOS-ESM/GEOSgcm_App/pull/201 should have closed it??!

**Closed by sanAkel** 2021-02-16 21:11 UTC
Labels: bug
