### ISSUE TITLE
Issue with MAPL_GetResource in develop

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#1956] opened 2023-02-03 22:12 UTC
I just tried running the model with MAPL's develop branch as of today (2/3/2023) and one gets a cavalcade of this which appears to be related to MAPL_GetResource:
```
pe=00031 FAIL at line=08297    MAPL_Generic.F90                         <status=-1>
pe=00032 FAIL at line=08297    MAPL_Generic.F90                         <status=-1>
pe=00033 FAIL at line=08297    MAPL_Generic.F90                         <status=-1>
pe=00034 FAIL at line=08297    MAPL_Generic.F90                         <status=-1>
pe=00035 FAIL at line=08297    MAPL_Generic.F90                         <status=-1>
pe=00036 FAIL at line=08297    MAPL_Generic.F90                         <status=-1>
pe=00037 FAIL at line=08297    MAPL_Generic.F90                         <status=-1>
pe=00038 FAIL at line=08297    MAPL_Generic.F90                         <status=-1>
pe=00039 FAIL at line=08297    MAPL_Generic.F90                         <status=-1>
pe=00040 FAIL at line=08297    MAPL_Generic.F90                         <status=-1>
pe=00041 FAIL at line=08297    MAPL_Generic.F90                         <status=-1>
pe=00042 FAIL at line=08297    MAPL_Generic.F90                         <status=-1>
pe=00043 FAIL at line=08297    MAPL_Generic.F90                         <status=-1>
```
at every step. This does not crash the code but not good none the less as gives an overwhelming amount of prints to the log.
@tclune informed me MAPL_GetResource has changed and been refactored. In base/MAPL_Resource.F90 he noticed a bare "return" i.e. not a _RETURN(_SUCCESS) which I fixed which did not fix the problem. However, after I changed this, I realized there are at least 4 more bare returns in that file. Maybe those also need to be fixed. I'm out of steam for the day so will try this on Monday.

**Comment by mathomp4** [comment] 2023-02-03 23:40
See also #1954

**Comment by tclune** [comment] 2023-02-06 16:22
@darianboggs Please give this some priority.   Might have to use a specific setup to trigger the issue.  @bena-nasa can presumably help you create a reproducer.  

And if debugging points outside the layer, please let us know.

**Comment by darianboggs** [comment] 2023-02-06 19:21
In my test runs, these resources: `IMPORT_CHECKPOINT_FILE`, `IMPORT_RESTART_FILE`, `INTERNAL_CHECKPOINT_FILE`, `INTERNAL_RESTART_FILE`, and `RECORD_FINAL` are not found in the ESMF_Config and there is no default provided in the `MAPL_GetResource` (interface) calls for these resources.

### Before Refactor
```
interface  MAPL_GetResource
      module procedure MAPL_GetResourceFromConfig_scalar
      module procedure MAPL_GetResourceFromMAPL_scalar
      module procedure MAPL_GetResource_array
end interface MAPL_GetResource
```
`MAPL_GetResourceFromMAPL_scalar` and `MAPL_GetResource_array` called `ESMF_ConfigFindLabel`.
If the resource label was not found, and there was no default value for the resource, both subroutines set `RC = ESMF_FAILURE` and immediately returned. The client calling procedure was left to check `RC` or ignore it.

### After Refactor
`MAPL_GetResourceFromMAPL_scalar` and `MAPL_GetResource_array` call `base/MAPL_Resource/MAPL_GetResource_config_array` and `base/MAPL_Resource/MAPL_GetResource_config_scalar`, respectively, which call `ESMF_ConfigFindLabel` and set `RC = ESMF_FAILURE` if the resource label is not found and there is no default value given. `MAPL_GetResourceFromMAPL_scalar` and `MAPL_GetResource_array` call the `_VERIFY` macro (through the `_RC` macro) and that produces the `FAIL` message.

### Resolution
I am working on a fix that restores the previous behavior with the new structure.

**Comment by mathomp4** [comment] 2023-02-06 19:49
Dang. Good detective work! I've been playing a bit on this as I'm waiting for some jobs to get through and I was going insane trying to figure it out. 

Pretty much means you wrote code that was too good and before we were sort of checking the return code sometimes, but not always...and depending on the no-check for "good" behavior

**Comment by darianboggs** [comment] 2023-02-06 21:02
Got a fix. Compiling now. Some client code that uses `MAPL_GetResource` handles `RC` values itself. It basically uses the return code as a flag for conditional action rather than as a diagnostic. I don't know what best practice is, but I think of the return code as diagnostic. Our emphasis on verifying the return code in MAPL provides better diagnostics, but it is not compatible for cases where it is used for conditional behavior.

**Comment by darianboggs** [comment] 2023-02-07 04:09
Bug fix eliminated the problem, but there are still fail messages from a different place. Somewhere else the refactored `MAPL_GetResource` may be returning an unexpected value.

**Comment by tclune** [comment] 2023-02-07 14:11
> I don't know what best practice is, but I think of the return code as diagnostic. Our emphasis on verifying the return code in MAPL provides better diagnostics, but it is not compatible for cases where it is used for conditional behavior.

In many cases where we previously had this anti-pattern, it turned out that ESMF had additional optional flags that could have (should have) been used.   Basically one can check whether a thing exists (or is valid or whatever), and if you do that, then SUCCESS is returned in the RC, with the expectation that the user will check the other optional flag.   If humans were robots, this would not be an improvement, but always being able to just use the `_RC` is desirable so that it is obvious to the next person what is going on.

And if MAPL just used `_RC` more consistently, then these odd cases would be a bit more glaring and less likely to be glossed over.

Feel free to check for additional arguments in the offending calls and/or suggest a better canonical approach for these cases.   New eyes and all that ...

**Comment by darianboggs** [comment] 2023-02-08 15:07
Still getting (moving) errors:
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
GEOSgcm.x          000000000F675FDA  Unknown               Unknown  Unknown
libpthread-2.22.s  00002AAAD743CC10  Unknown               Unknown  Unknown
libMAPL.generic.s  00002AAABAFA2F8C  mapl_genericmod_m        8299  MAPL_Generic.F90
GEOSgcm.x          00000000068DBCBD  geos_moistgridcom        9171  GEOS_MoistGridComp.F90
```
... [SNIP] ...
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
GEOSgcm.x          000000000F675FDA  Unknown               Unknown  Unknown
libpthread-2.22.s  00002AAAD743CC10  Unknown               Unknown  Unknown
libMAPL.generic.s  00002AAABAFA2F8C  mapl_genericmod_m        8299  MAPL_Generic.F90
GEOSgcm.x          00000000068DBCBD  geos_moistgridcom        9171  GEOS_MoistGridComp.F90
```

Running with commit before refactor

**Comment by mathomp4** [comment] 2023-02-08 15:22
Hmm. If I had to guess, that would be a TimerOn or TimerOff call given it's in Moist and so far down. 

We...occasionally check the RC for `MAPL_TimerOn` and `MAPL_TimerOff`; it's random.

**Comment by darianboggs** [comment] 2023-02-08 18:22
Ran with MAPL commit before the refactor. No problem. Not surprising.

**Comment by darianboggs** [comment] 2023-02-08 18:53
Edited all the portions of the refactored MAPL_GetResource that set and check RC codes. Running to see if it works, and then I'll add back the RC code logic until the bug recurs.

**Comment by darianboggs** [comment] 2023-02-09 05:06
It appears that the problem is with the check for no label and no default. It needs to pass return the nonzero RC with running the _VERIFY.

**Comment by darianboggs** [comment] 2023-02-10 05:43
It worked. I'll run full zero-diff test tomorrow.
```mermaid
flowchart TB;
    idclient[(client procedures)]-.-generic/MAPL_GenericMod-.->idintf[/MAPL_GetResource\]-->idproc([module procedure])
    idproc-.->idmod[base/MAPL_ResourceMod]
    idmod-.->id2[[MAPL_GetResourceFromMAPL_scalar]]-->id3[[base/MAPL_GetResource_config_scalar]]
    idmod-.->id4[[MAPL_GetResourceFromConfig_scalar]]-->id3
    idmod-.->id5[[MAPL_GetResource_array]]-->id6[[MAPL_GetResource_config_array]]
```
The issue is that the _module procedure_ subroutines (see above) cannot use the `_RETURN(ERROR)` macro, where `ERROR` is a non-zero return code, but they can use the `_RETURN(_SUCCESS)` macro. Instead, they must use the `value_is_set` _intent(out)_ logical argument of the _base/MAPL_ResourceMod_ subroutines to determine if the value was set (by config or default). If it was set successfully, the normal `_RETURN(_SUCCESS)` macro is used. If it was not set successfully, `rc` is explicitly set to `ESMF_FAILURE`
 
[https://github.com/GEOS-ESM/MAPL/blob/6dd955469a158afe9f1d3441b08865e8338b8940/generic/MAPL_Generic.F90#L8298-L8306](url)

This is necessary because some client code (_MAPL_ and non-_MAPL_) uses the `rc` code as a flag for conditional code instead of merely as an indication of error. This is incompatible with the error handling system including macros. Therefore, the error handling system may not necessarily yield useful info from `MAPL_GetResource`. This behavior may not be desirable, and it may be changed in the future.

**Comment by mathomp4** [comment] 2023-02-10 13:19
@darianboggs Wow. Complex. Good job finding this!

Hopefully with this, we can overload the array version for state and config safely. I was always reticent to do that.

**Comment by darianboggs** [comment] 2023-02-11 03:02
FYI: The overload of the array version should be straightforward, as it mirrors the scalar version in the refactored design. I anticipated the overload, and I will implement it when this PR is closed.

**Comment by darianboggs** [comment] 2023-02-13 04:42
I pushed up the bugfix to the branch: bugfix/wdboggs/fix_refactor_error

I decided to create the PR on Monday morning when I can monitor it for problems.

**Comment by darianboggs** [comment] 2023-02-13 16:50
PR merged. Close issue.

**Closed by darianboggs** 2023-02-13 16:50 UTC
Labels: bug
