### ISSUE TITLE
ESMF time interval division gives different results despite identical inputs in different executions

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#1416] opened 2022-03-08 14:42 UTC
While testing for the next CF system, the CF developers found an issue where ExtData was insisting it could not find the correct file despite the fact the files existed for the current time. This was with MAPL v2.7.1 and the file was one needed for the CO2 gocart grid comp. Worse this problem only shows up at c360 when running the full model. I tried ingesting the same files used by CO2 grid comp in my ExtDataDriver.x and even running that at c360 on the same core counts I could not reproduce this. The problem ultimately was this line in ExtData.
```
n = max(0,floor((cTime-item%reff_time)/item%frequency))
```
The pointer of this line is given the reference time and the frequency, find the closest time that is the reference time plus a multiple of the frequency. The problem is that given two identical runs other than the resolution and layout (so same RC files) this ESMF time interval division was giving different answers for one entry. At C24,C48,C90, it gave one answer which was correct, in that it brought you to a time that was within a frequency unit of the target time. But at c360 it gave a different answer which overshoots the current time and then ExtData can't find the bracketing time it needs and fails.
I'm stumped as this seems to be reproducible but in the model so far, but not in ExtDataDriver.x when ingesting the same files at the same application resolution!
As "fix" I think we need to avoid time interval division and I am going to make a patch that replaces this line with this a subroutine along these lines:
```
  function compute_closest_time(current_time,reference_time,frequency,rc) result(closest_time)
     type(ESMF_Time) :: closest_time
     type(ESMF_Time), intent(in) :: current_time
     type(ESMF_Time), intent(in) :: reference_time
     type(ESMF_TimeInterval), intent(in) :: frequency
     integer, optional, intent(out) :: rc

     integer :: status

     closest_time = reference_time
     if (current_time > reference_time) then
        do while(ESMF_TimeIntervalAbsValue(current_time-closest_time) > frequency)
           closest_time = closest_time + frequency
        end do
      else
          do while(ESMF_TimeIntervalAbsValue(current_time-closest_time) > frequency)
           closest_time = closest_time - frequency
        end do
     end if
     _RETURN(_SUCCESS)
  end function compute_closest_time
```
Essentially brute force this and simply avoid dividing any time intervals. I can keep trying to reproduce this, but this seems to be some problem within ESMF. Truly baffling.

**Comment by tclune** [comment] 2022-03-08 14:47
Since `ESMF_Time` and `ESMF_TimeInterval` perform _exact_ arithmetic, this cannot be a rounding error.    So either this is a bug in ESMF that should be reported, or is worth digging a bit more into.  (Or I've misunderstood in my first reading -- always possible.)

Indeed, the entire reason that ESMF implement exact arithmetic for time was to avoid this sort of issue.

For the case that breaks in the model, could you dump out the exact values of:

- cTime
- item%reff_time
- item%frequency
- the result of the division
- the result of floor

We need to document exactly where a "bad" value is seen and the report to ESMF if it looks like a problem on their end or see where we have made a bad assumption.

**Comment by mathomp4** [comment] 2022-03-08 16:52
Those TimeIntervals look odd. This:
```
P0Y1M0DT0H0M0S
```
is a duration of 1 month and this:
```
P0Y0M22DT15H0M0S
```
is a duration of 22 days, 15 hours.

**Comment by bena-nasa** [comment] 2022-03-08 16:57
The first time interval should be a month. 
Notice in the c90 case the print of the mod outputs garbage
I don't use the mod, I was just printing it to see what it gave.

**Comment by mathomp4** [comment] 2022-03-08 17:01
Ohhh. Yeah. ExtData!  I was expecting things like "6 hours" or "15 minutes" or something because my brain was in History land. 😄 

Though I suppose we can do monthly history now...

**Comment by mathomp4** [comment] 2022-03-08 17:02
But, yes, I agree that `^X` is not a good ISO 8601 format.

**Comment by bena-nasa** [comment] 2022-03-08 17:15
Maybe the CAP.rc's weren't the same, I just copied in the CAP.rc from the C90 and now it's work. I thought both these CAP.rc's were whatever you get from the makeoneday script, I changed the C90 one to a job_segment to match the DT, so I didn't have to wait for the full day to run to see the results, I thought, lets make sure the job_segments are the same, so I copied over the C90 one to c360 and now it is working and I can't get the c360 job to fail :(

**Comment by bena-nasa** [comment] 2022-03-08 17:23
well, this is great, now I can't reproduce the error!

**Comment by tclune** [comment] 2022-03-08 17:24
One more "probably something uninitialized" thing for our collection.   Ugh.

**Comment by mathomp4** [comment] 2022-05-02 13:21
@bena-nasa Did you fix this?

**Comment by mathomp4** [comment] 2022-09-10 16:52
I'm un-staling until @bena-nasa can comment

**Comment by mathomp4** [comment] 2022-09-12 16:53
Closing as this is sort of nigh-unreproducible. And per @bena-nasa, ExtData2G doesn't do this.

**Closed by mathomp4** 2022-09-12 16:53 UTC
Labels: bug
