### ISSUE TITLE
Model hang in finalize after EGRESS

### ISSUE THREAD

**Issue by wmputman** [GEOS-ESM/MAPL#499] opened 2020-07-13 15:20 UTC
The latest develo pcode is hanging again after writing the EGRESS file. I thought there was a fix but cannot find it...

**Comment by wmputman** [comment] 2020-07-13 15:58
@mathomp4 the issue is recurring for me on every run in my 12km Replay+Fcst sandbox.  I can login to the head node and kill the GOESgcm.x processes to free up the run and the report back is this:

Model Throughput:       14.239 days per day
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source
GEOSgcm.x          000000000595554E  Unknown               Unknown  Unknown
libpthread-2.22.s  00002AAAB66F9C10  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00002AAAB5BD8C0E  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00002AAAB5646B04  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00002AAAB5C028E3  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00002AAAB57C1929  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00002AAAB555E21C  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00002AAAB555F428  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00002AAAB55CA313  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00002AAAB55B2D8E  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00002AAAB56CF925  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00002AAAB555F75E  MPI_Barrier           Unknown  Unknown
libmpifort.so.12.  00002AAAB517173C  pmpi_barrier          Unknown  Unknown
GEOSgcm.x          000000000575FB51  pfio_directoryser         569  DirectoryService.F90
GEOSgcm.x          0000000005110212  mapl_capmod_mp_ru         206  MAPL_Cap.F90
GEOSgcm.x          000000000510FAFF  mapl_capmod_mp_ru         182  MAPL_Cap.F90
GEOSgcm.x          0000000000425E6F  MAIN__                     32  GEOSgcm.F90
GEOSgcm.x          00000000004244AE  Unknown               Unknown  Unknown
libc-2.22.so       00002AAAB725E725  __libc_start_main     Unknown  Unknown
GEOSgcm.x          00000000004243A9  Unknown               Unknown  Unknown
forrtl: error (78): process killed (SIGTERM)

**Comment by mathomp4** [comment] 2020-07-13 16:10
@wmputman Can you point us to the build and experiment that caused this? I'm first wondering what version of MAPL you are running.

**Comment by wmputman** [comment] 2020-07-13 16:27
Everything is the latest develop code (as of last week):

 /discover/nobackup/projects/gmao/osse2/GIT/GEOS-develop-head/GEOSgcm


-- Bill Putman

William M Putman
Global Modeling and Assimilation Office
NASA Goddard Space Flight Center
Cell: 240-778-5697
Desk: 301-286-2599

**Comment by mathomp4** [comment] 2020-07-13 16:55
Okay. I'm going to ping/add in @weiyuan-jiang. The fact that it's dying/stalling on:

https://github.com/GEOS-ESM/MAPL/blob/2a1834a122ce5be5e0166e4463e70e78cce189fa/GMAO_pFIO/DirectoryService.F90#L569

makes me wonder if somehow having IOSERVER_NODES on is causing something odd.

**Comment by atrayano** [comment] 2020-07-13 17:00
@mathomp4 , @wmputman is using v2.1.5 of MAPL. If I remember correctly, we fixed a very similar issue on the develop branch few weeks ago (Weiyuan has pushed his changes to close some MPI_win in pfio for the io server). I thought that these changes were pulled into v2.1.5, so I am very surprised

**Comment by wmputman** [comment] 2020-07-13 17:14
I just had  a similar hang during the run (well before EGRESS)

forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source
GEOSgcm.x          000000000595554E  Unknown               Unknown  Unknown
libpthread-2.22.s  00002AAAB66F9C10  Unknown               Unknown  Unknown
libpsm2.so.2.1     00002AB04A4E6C6B  Unknown               Unknown  Unknown
libpsm2.so.2.1     00002AB04A4E4ACF  Unknown               Unknown  Unknown
libpsm2.so.2.1     00002AB04A4DB2BB  psm2_mq_iprobe2       Unknown  Unknown
libpsmx2-fi.so     00002AB04A2688C6  Unknown               Unknown  Unknown
libpsmx2-fi.so     00002AB04A268CE1  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00002AAAB5A94E8C  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00002AAAB5A9563A  PMPI_Probe            Unknown  Unknown
libmpifort.so.12.  00002AAAB5183244  mpi_probe__           Unknown  Unknown
GEOSgcm.x          00000000057601CB  pfio_mpisocketmod         111  MpiSocket.F90
GEOSgcm.x          000000000579F672  pfio_clientthread         226  ClientThread.F90
GEOSgcm.x          00000000057A6DC9  pfio_clientmanage         161  ClientManager.F90
GEOSgcm.x          00000000052D5F49  mapl_newcfiomod_m         323  MAPL_newCFIO.F90
GEOSgcm.x          0000000005305CB9  mapl_historygridc        2983  MAPL_HistoryGridComp.F90
libesmf_fullylink  00002AAAB19369B1  _ZN5ESMCI6FTable1     Unknown  Unknown
libesmf_fullylink  00002AAAB193A2BF  ESMCI_FTableCallE     Unknown  Unknown
libesmf_fullylink  00002AAAB1E17195  _ZN5ESMCI2VM5ente     Unknown  Unknown
libesmf_fullylink  00002AAAB1937E7A  c_esmc_ftablecall     Unknown  Unknown
libesmf_fullylink  00002AAAB2041871  esmf_compmod_mp_e     Unknown  Unknown
libesmf_fullylink  00002AAAB22365CF  esmf_gridcompmod_     Unknown  Unknown
GEOSgcm.x          0000000005097BA0  mapl_genericmod_m        1835  MAPL_Generic.F90

**Comment by wmputman** [comment] 2020-07-13 18:56
@mathomp4 @weiyuan-jiang: Without the IO_SERVER my jobs are running fine...

**Comment by weiyuan-jiang** [comment] 2020-07-13 18:59
> @mathomp4 , @wmputman is using v2.1.5 of MAPL. If I remember correctly, we fixed a very similar issue on the develop branch few weeks ago (Weiyuan has pushed his changes to close some MPI_win in pfio for the io server). I thought that these changes were pulled into v2.1.5, so I am very surprised

I believe this is different issue.  My fix before was for Mpi_Finalize failure.  This error seems to me that some processes are stuck somewhere and could not reach the barrier point

**Comment by mathomp4** [comment] 2020-07-13 18:59
@wmputman Ah. That is a clue. @weiyuan-jiang knows the subcommunicator bits of MAPL/pfio better than anyone so hopefully he can look through MAPL to see what might be causing it. I took a brief glance and it looked okay to me, but I can get lost in OO code.

**Comment by bena-nasa** [comment] 2020-07-13 19:12
@wputman How many IO server nodes were you using when this was hanging?

**Comment by wmputman** [comment] 2020-07-13 19:34
@bena-nasa I was using 5 IO nodes. And yes I had WRITE_RESTART_BY_OSERVER: NO in the AGCM.rc

**Comment by weiyuan-jiang** [comment] 2020-07-14 12:05
@wmputman Do you mean it is running fine now without IO SERVERS here  /discover/nobackup/projects/gmao/osse2/Ops12KM_R/forecasts_EC/12KM/Jason-c720_L181_NL_NH_GFDL_EC  ? Do you have problem with coarser resolution like 25 km with IO SERVER?

**Comment by wmputman** [comment] 2020-07-14 14:38
That's correct, it is running fine there without IO Servers. I haven't tried lower resolutions

**Comment by bena-nasa** [comment] 2020-07-14 14:47
c720, 72 levels, cube ocean stock setup (only 16*96 processors + ioserver nodes) you get from gcm_setup runs fine. I'll keep try to push it to higher core counts as the queues permit to see if I can reproduce anything.

**Comment by wmputman** [comment] 2020-07-14 17:24
Yes, I did a stock setup with c360 72L in replay mode, similar to my c720 181L setup.  The c360 72L case is running fine with the Io Server:

Directory: /discover/nobackup/projects/gmao/osse2/Ops12KM_R/forecasts_EC/25KM/DYAMONDv2_Beta10p13_25KM_72L_1MOM_ERA5

**Comment by weiyuan-jiang** [comment] 2020-07-14 18:34
Maybe we can try 14 IO nodes ( since you have 14 collections)

**Comment by bena-nasa** [comment] 2020-07-14 21:23
We run with around that many collections with the standard history.

**Comment by bena-nasa** [comment] 2020-07-15 19:03
I'm trying reproduce this. Thus far I've tried a c720/72 level run with Bill's history at the same core count he is using 16200 as well as a smaller job at around 10000 cores, both on the skylakes. Both jobs have just hung, I was watching the one at 16200 cores, it got about 3 hours into the run, then just hung until the job timed out.
setenv I_MPI_DAPL_UD enable
setenv I_MPI_ADJUST_ALLREDUCE 12
setenv I_MPI_ADJUST_GATHERV 3

# This flag prints out the Intel MPI state. Uncomment if needed
#setenv I_MPI_DEBUG 9
setenv I_MPI_SHM_HEAP_VSIZE 512
setenv PSM2_MEMORY large
setenv I_MPI_EXTRA_FILESYSTEM 1
setenv I_MPI_EXTRA_FILESYSTEM_FORCE gpfs
setenv ROMIO_FSTYPE_FORCE "gpfs:

Bill appears to be running this these:
setenv I_MPI_FABRICS shm:ofa
setenv I_MPI_FABRICS_LIST ofa,dapl
setenv PSM2_MEMORY large
setenv I_MPI_ADJUST_GATHERV 3
setenv I_MPI_ADJUST_ALLREDUCE 12
setenv I_MPI_SHM_HEAP_VSIZE 512
setenv I_MPI_EXTRA_FILESYSTEM 1
setenv ROMIO_FSTYPE_FORCE "gpfs:"
setenv I_MPI_DEBUG 6

I'll try running with these but thus far I have not even been able to run the model for a full day, let alone see it hang at the end.

**Comment by bena-nasa** [comment] 2020-07-16 18:05
So both myself and @mathomp4 have now found we are unable to even run the model to completion for a day when using the 405 nodes = 16200 cores for the model + some ioserver nodes. @mathomp4 is going to try other MPI stacks and when I can get a giant interactively job do more tests. For both of us, the model simply hangs several model hours into the run. The time is variable when it happens. I did try one one where I did not spin off separate server nodes. That did not hang, although it could not even get through 1 day of model time in 1 wall hour as the writes were so slow.

**Comment by wmputman** [comment] 2020-07-16 18:11
@bena-nasa that is consistent with my experience now as well. If you go into the head node and kill those jobs that hang you'll see the following traceback:

GEOSgcm.x 00000000057601CB pfio_mpisocketmod 111 MpiSocket.F90
GEOSgcm.x 000000000579F672 pfio_clientthread 226 ClientThread.F90
GEOSgcm.x 00000000057A6DC9 pfio_clientmanage 161 ClientManager.F90
GEOSgcm.x 00000000052D5F49 mapl_newcfiomod_m 323 MAPL_newCFIO.F90
GEOSgcm.x 0000000005305CB9 mapl_historygridc 2983 MAPL_HistoryGridComp.F90

**Comment by mathomp4** [comment] 2020-07-16 19:01
As I said to @bena-nasa on Teams, so far (🤞 ) a run with Intel 19.1.1 + Intel MPI 19.1.1 seems to be running better:
```
/discover/nobackup/mathomp4/Experiments/test_bill_server_c720_big/slurm-38470026.out
```

I'm also trying to compile MVAPICH2 for Omnipath as well as perhaps a different MPI stack for testing.

**Comment by mathomp4** [comment] 2020-07-16 19:04
Note: I chose Intel 19.1.1 + IMPI 19.1.1 because of easiness. I do also have an Intel 18.0.5 + IMPI 19.1.1 baselibs if one doesn't want to change the compiler version.

**Comment by wmputman** [comment] 2020-07-17 14:15
Currently I'm running on SLES12 with: ifort_18.0.5.274-intelmpi_19.1.0.166 and that case hangs for me.

So, why aren't we pushing to ifort_20.0.0.166-intelmpi_20.0.0.166?

**Comment by wmputman** [comment] 2020-07-17 16:06
The ifort_20.0.0.166-intelmpi_20.0.0.166 combination hangs, when using 5 IO nodes and 400 GCM nodes.  I'm trying a small configuration 270 GCM nodes and 2 IO nodes.

**Comment by mathomp4** [comment] 2020-07-17 18:23
Note to @wmputman: 20.0.0.166 is equivalent to 19.1.0.166. The "latest" version is 19.1.1.217. If you'd like to try that, you can use:
```
/gpfsm/dhome/mathomp4/GitG5Modules/SLES12/6.0.13/g5_modules.intel1911.impi1911
```
As for why we haven't moved to Intel 19.1 (aka Intel 20), I believe it is non-zero-diff to Intel 19.0. I have no problem with moving, the GEOSldas folks *require* Intel 19 as do the JEDI. So, perhaps we should move after the next GEOSgcm is released.

**Comment by wmputman** [comment] 2020-07-21 14:17
I'm still experiencing random hangs after EGRESS... any word on what the issues are?

**Comment by weiyuan-jiang** [comment] 2020-07-21 14:52
@wmputman . I still have no clue. I am looking through the codes to see if there is memory leak that leads to the "death" of some writing processes.

**Comment by mathomp4** [comment] 2020-07-21 15:06
Note: I also built an Intel 19.1.1/Open MPI 4.0.4 stack and like Intel 19.1.1/IMPI 19.1.1, I was able to run the model for a day, but it ran out of time trying to write restarts again. Since this was Open MPI, I did have `WRITE_RESTART_BY_OSERVER: YES`, but it didn't seem to help. (If it's like previous experience, without this flag, Open MPI would be order(s) of magnitude slower with restarts.)

When Ben returns, I'll ask him to give this combo a try and see if he can see anything. I'm also going to try a `RECORD_FINAL: NO` run just to see if it can get to `EGRESS` and stall there!

**Comment by mathomp4** [comment] 2020-07-21 19:46
I just tried my Open MPI with `RECORD_FINAL: NO` and that finished just fine. I will note for @weiyuan-jiang or @bena-nasa that it looks like `EGRESS` is written before all of history is done:
```
.rw-r--r-- mathomp4 g0620    16 B  Tue Jul 21 12:03:29 2020  cap_restart
.rw-r--r-- mathomp4 g0620     0 B  Tue Jul 21 12:03:29 2020  EGRESS
.rw-r--r-- mathomp4 g0620     1 MB Tue Jul 21 12:03:33 2020  Jason-c720_L181_NL_NH_GFDL_EC.geosgcm_meltwtr.20150415_0900z.nc4
.rw-r--r-- mathomp4 g0620  20.9 MB Tue Jul 21 12:03:33 2020  Jason-c720_L181_NL_NH_GFDL_EC.geosgcm_landice.20150415_0900z.nc4
.rw-r--r-- mathomp4 g0620     5 MB Tue Jul 21 12:03:33 2020  Jason-c720_L181_NL_NH_GFDL_EC.geosgcm_budi.20150415_2100z.nc4
.rw-r--r-- mathomp4 g0620  20.9 MB Tue Jul 21 12:03:33 2020  Jason-c720_L181_NL_NH_GFDL_EC.geosgcm_buda.20150415_1930z.nc4
.rw-r--r-- mathomp4 g0620 148.8 MB Tue Jul 21 12:03:33 2020  Jason-c720_L181_NL_NH_GFDL_EC.geosgcm_snowlayer.20150415_0900z.nc4
.rw-r--r-- mathomp4 g0620 152.3 MB Tue Jul 21 12:03:33 2020  Jason-c720_L181_NL_NH_GFDL_EC.geosgcm_surf.20150415_1930z.nc4
.rw-r--r-- mathomp4 g0620 191.4 MB Tue Jul 21 12:03:34 2020  Jason-c720_L181_NL_NH_GFDL_EC.geosgcm_iau.20150415_1800z.nc4
.rw-r--r-- mathomp4 g0620 432.4 MB Tue Jul 21 12:03:34 2020  Jason-c720_L181_NL_NH_GFDL_EC.geosgcm_gwd.20150415_0900z.nc4
.rw-r--r-- mathomp4 g0620 574.2 MB Tue Jul 21 12:03:34 2020  Jason-c720_L181_NL_NH_GFDL_EC.geosgcm_turb.20150415_0900z.nc4
.rw-r--r-- mathomp4 g0620   1.4 GB Tue Jul 21 12:03:35 2020  Jason-c720_L181_NL_NH_GFDL_EC.geosgcm_moist.20150415_0900z.nc4
.rw-r--r-- mathomp4 g0620   1.2 GB Tue Jul 21 12:03:35 2020  Jason-c720_L181_NL_NH_GFDL_EC.geosgcm_tend.20150415_0900z.nc4
.rw-r--r-- mathomp4 g0620 157.1 MB Tue Jul 21 12:03:50 2020  Jason-c720_L181_NL_NH_GFDL_EC.tavg1_2d_flx_Nx.20150415_2030z.nc4
.rw-r--r-- mathomp4 g0620 390.3 MB Tue Jul 21 12:04:11 2020  Jason-c720_L181_NL_NH_GFDL_EC.inst1_2d_asm_Nx.20150415_2100z.nc4
```
Not sure that means anything other than we are asynchronous.

**Comment by mathomp4** [comment] 2020-07-21 19:47
Also, I have installed Intel 2021 Beta on discover and I'm going to try this case with that as well. The Beta included Intel MPI 2021 Beta so maybe something is different?

**Comment by atrayano** [comment] 2020-07-21 19:55
@mathomp4 The fact that the EGRESS file is written before history output is an artifact that we are asynchronizous. There is a barrier before writing EGRESS but only for the "model" CPUs. The fact that EGRESS gets written only proves that "model" CPUs cleared the barrier and the handing is due to IO server.

**Comment by mathomp4** [comment] 2020-07-21 21:06
Interesting: Using the Intel Beta, I was able to complete a full day run at 410 nodes for the first time. Even the restarts wrote out in "normal" time. And I got an `EGRESS`. Took 43 minutes of wall time which is...I don't know. Good? First time it completed so I have no baseline. I thought about looking at the throughput from MAPL but:
```
Model Throughput:       -0.407 days per day
```
That's not good.  

The Run method seemed highly dominated by History as well. Not sure if that's expected. 

I've re-submitted to make sure it wasn't a one-off fluke

**Comment by atrayano** [comment] 2020-07-21 21:13
How do we get negative throughput? Unless somehow the OS made a time correction (i.e. adjusted/synchronized it own clock backwards) during a time step???

**Comment by mathomp4** [comment] 2020-07-22 14:34
> How do we get negative throughput? Unless somehow the OS made a time correction (i.e. adjusted/synchronized it own clock backwards) during a time step???

Not sure but my second (also successful) run didn't do it! 

I think @tclune long ago figured out a similar negative was due to an overflowing integer or something in our main MAPL timers? It's possible this throughput timer was never fixed the same way so this was the one in a million or whatever chance.

**Comment by tclune** [comment] 2020-07-22 14:39
Yeah - I can't remember the odds in detail.   I think when it was a 32 bit integer in the timer that the odds were like one in 5 for a 12 hour run.   With the 64 bit integer it is much rarer, but not as much as you might think because it also has a smaller clock tick.  But certainly rare enough that it should be investigated when we see it.  (Unless the 32 bit integers got back in there.)

**Comment by weiyuan-jiang** [comment] 2020-08-04 03:39
@bena-nasa Would you please help me try the branch feature/wjiang/io_2nd_layer . By default, it still uses MpiServer. I guess I have fixed something suspicious.

**Comment by mathomp4** [comment] 2021-02-22 14:34
@weiyuan-jiang @bena-nasa @tclune Can we close this issue? I don't think Bill is hanging at EGRESS anymore (if anything he hangs at "ingress" at init time).

**Comment by tclune** [comment] 2021-02-22 19:47
Yes - this can be closed.

**Closed by tclune** 2021-02-22 19:47 UTC
