### ISSUE TITLE
New ESMF Logging Errors in MAPL

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#742] opened 2021-03-08 15:14 UTC
My nightly tests on Thursday night (Mar 04) triggered my "Check of ESMF errors". And indeed, when using MAPL `develop`, I now have `PET00.ESMF_LogFile` files with:
```
20210308 022128.787 ERROR            PET00 ESMF_StateAPI.cppF90:3071 ESMF_StateGet Not found  -  no ESMF_Field found named: LS_PRCP+CU2DRAINMOVE+CU2DSNOWMOVE
20210308 022128.787 ERROR            PET00 ESMF_StateAPI.cppF90:3071 ESMF_StateGet Not found  -  no ESMF_Field found named: CN_PRCP-CU2DRAINMOVE-CU2DSNOWMOVE
```
If I had to guess, I'm going with this commit: https://github.com/GEOS-ESM/MAPL/commit/56c23620da69b1d0d38d711161247cb2cdfc447b from @bena-nasa as it has a new `ESMF_StateGet` call, but I don't see why it's different than the other `ESMF_StateGet` calls in `MAPL_HistoryGridComp.F90`.

I'm going to try and figure this out myself, but I might need @atrayano to help me remember how we fixed a lot of these.

**Comment by atrayano** [comment] 2021-03-08 15:33
@mathomp4 Are we testing expressions in History with your nightly tests? The "not found" field looks like expression to me. Unfortunately, ESMF_StateGet does not have a "nice" ifPresent argument, so we could query how many items were in the state, allocate an array for the list, get the list, and check if the field is there, which is very, very tedious.

**Comment by mathomp4** [comment] 2021-03-08 15:41
@atrayano Yes. We are. The "default" AGCM `HISTORY.rc` has:
```
                          'LS_PRCP+CU2DRAINMOVE+CU2DSNOWMOVE' , 'MOIST' , 'LSORIG' ,
                          'CN_PRCP-CU2DRAINMOVE-CU2DSNOWMOVE' , 'MOIST' , 'CNORIG' ,
```
in it, but they've been there since Git started. So we are somehow avoiding this everywhere else.

I did see [this interface](http://earthsystemmodeling.org/docs/release/ESMF_8_0_1/ESMF_refdoc/node4.html#SECTION04077900000000000000) to `ESMF_StateGet` which says it can be used to see if it returns `ESMF_STATEITEM_NOTFOUND`. I tried swapping out:
https://github.com/GEOS-ESM/MAPL/blob/aa007cd980cb6281b7e22ce98b30b3788de0aa41/gridcomps/History/MAPL_HistoryGridComp.F90#L4746
with:
```fortran
call ESMF_StateGet(state,fields(1,m),itemType,rc=status)
```
being naive but it just sort of...nuked everything after that because I don't know the code. 😄 I might have to put this in the hands of @bena-nasa as History is complex ESMF compared to what I'm used to!

**Comment by atrayano** [comment] 2021-03-08 15:50
@mathomp4 Even if your scheme would have worked, it is already too late  to check for the status- by the time the call returns, it might have already put the errors in the ESMF log file(s)

**Comment by atrayano** [comment] 2021-03-08 15:59
I think the reason this was not reporting errors before, was that couple of days ago @bena-nasa changed the strategy in History: before we were parsing the entry to check if it is an expression, and only after that we fetched the fields. Now we are checking if the entry is in the state first (this helped UFS runs) but obviously triggered the above error. So we need to do the tedious check to avoid triggering ESMF errlog messages

**Comment by mathomp4** [comment] 2021-03-08 16:53
@atrayano Sounds good. I've already trained my brain to ignore the SCM failures, I can train it to ignore these as well for a bit

**Comment by bena-nasa** [comment] 2021-03-08 17:58
Wow, late to the party for me. Yes, the issue is that I changed the logic a bit to detect if a string is an expression or not. First I check if the string is actually a field in the state but as Atanas said, there is no isPresent type argument for ESMF_StateGet. To eliminate this I would need to get the complete item list from the state, then loop over and see if any items match the string, and then make sure the item is a field. I didn't think about this. If our goal is no ESMF warnings like this I would have to do that. Seems like a useful MAPL utility function.

**Comment by mathomp4** [comment] 2021-03-08 18:37
Maybe we should propose something to ESMF? I know @tclune has said if we contribute, they might turn on issues for us!

But fixing this could also be *deep* inside the C++. I could edit the interface but beyond that...

**Comment by mathomp4** [comment] 2021-03-18 12:11
I'm changing the title of this. Turns out this error is also in MAPL 2.6.3. How do I know this? Well, last night Scott took an update PR to MAPL 2.6.3 and:
```
Runtype         Clone Build Build Time Ctest/Run Run/Comp/ESMF  Regress/Succ MAPL Comp Regrid Run/Comp SCM Run/Comp NAS Xfer NAS Comp
-------         ----- ----- ---------- --------- -------------  ------------ --------- --------------- ------------ -------- --------
default         pass  pass  27 min      -- / --  pass/pass/FAIL pass/pass     --       pass/FAIL       FAIL/FAIL    pass      --    
debug            --   pass   9 min      -- / --  pass/pass/FAIL pass/pass     --        -- / --         -- / --     pass      --    
replay           --    --    --         -- / --  pass/pass/FAIL pass/pass     --        -- / --         -- / --     pass      --    
repnoinc         --    --    --         -- / --  pass/pass/FAIL pass/pass     --        -- / --         -- / --     pass      --    
data             --    --    --         -- / --  pass/pass/FAIL pass/pass     --        -- / --         -- / --     pass      --    
ops181           --    --    --         -- / --  pass/pass/FAIL pass/pass     --        -- / --         -- / --     pass      --    
dasmode          --    --    --         -- / --  pass/pass/FAIL pass/pass     --        -- / --         -- / --     pass      --    
newland          --    --    --         -- / --  pass/pass/FAIL pass/pass     --        -- / --         -- / --     pass      --    
mom5             --    --    --         -- / --  pass/pass/pass  -- / --      --        -- / --         -- / --     pass      --    
mom6             --    --    --         -- / --  pass/pass/pass  -- / --      --        -- / --         -- / --     pass      --    
agg              --   pass  28 min      -- / --  pass/pass/FAIL  -- / --      --        -- / --         -- / --     pass      --    
gnu             pass  pass  20 min      -- / --  pass/pass/FAIL pass/pass     --        -- / --         -- / --     pass      --    
gnudebug         --   pass  13 min      -- / --  pass/pass/FAIL pass/pass     --        -- / --         -- / --     pass      --    
gnuagg           --   pass  19 min      -- / --  pass/pass/FAIL  -- / --      --        -- / --         -- / --     pass      --    
mapldev         pass  pass  26 min     pass/pass pass/pass/FAIL pass/pass    pass      pass/FAIL       FAIL/FAIL    pass      --    
mapldevrep       --    --    --         -- / --  pass/pass/FAIL pass/pass    pass       -- / --         -- / --     pass      --    
mapldevrepnoinc  --    --    --         -- / --  pass/pass/FAIL pass/pass    pass       -- / --         -- / --     pass      --    
mapldevdebug     --   pass   9 min     pass/pass pass/pass/FAIL pass/pass    pass       -- / --         -- / --     pass      --    
mapldevmom5      --    --    --         -- / --  pass/pass/pass  -- / --     pass       -- / --         -- / --     pass      --    
mapldevmom6      --    --    --         -- / --  pass/pass/pass  -- / --     pass       -- / --         -- / --     pass      --    
gnumapldev      pass  pass  20 min     pass/pass pass/pass/FAIL pass/pass    pass       -- / --         -- / --     pass      --    
gnumapldevdebug  --   pass  14 min     pass/pass pass/pass/FAIL pass/pass    pass       -- / --         -- / --     pass      --    
```
ESMF logging errors everywhere!

**Comment by mathomp4** [comment] 2021-03-18 12:12
Note: MOM5 and MOM6 runs do not show the error because they use a different history.

**Comment by atrayano** [comment] 2021-03-19 00:04
@mathomp4 I fixed the ESMF errors in the PET log files related to the expression parsing in History. I had to change only a single line in History. I have not committed my changes yet, because in the process I discovered also yet another (different) entry in the PET*.log files:

20210318 195333.847 ERROR            PET00 ESMF_Clock.F90:887 ESMF_ClockGetAlarm() Failure  - Internal subroutine call returned Error

It will be a lot easier to track these by using a debugger and setting a breakpoint in ESMF_Breakpoint. But at the moment I cannot find a recent baselibs (I am building with 6.0.22) that has  ESMF compiled with -g. Could you point me to one if exists, or if not, could you build one? Thanks!

**Comment by mathomp4** [comment] 2021-03-22 12:16
I can confirm that #766 will close this. My nightly tests show that all the MAPL `develop` tests do not have ESMF errors logged. Thanks, @atrayano!

**Closed** 2021-04-28 18:12 UTC
Labels: bug
