### ISSUE TITLE
Output conversion error occurs in MAPL built in debug mode

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/MAPL#723] opened 2021-02-24 20:53 UTC
UFS-GOCART crashes with the following error message when built with MAPL compiled in debug mode (`CMAKE_BUILD_TYPE=Debug`):
```
  0: forrtl: error (63): output conversion error, unit 6, file /proc/208081/fd/1
  0: Image              PC                Routine            Line        Source             
  0: ufs_model          000000000A198C5B  Unknown               Unknown  Unknown
  0: ufs_model          000000000A1FD4A7  Unknown               Unknown  Unknown
  0: libMAPL.cap.so     00002AB637B8A03D  mapl_capgridcompm        1227  MAPL_CapGridComp.F90
  0: libMAPL.cap.so     00002AB637B838CB  mapl_capgridcompm        1080  MAPL_CapGridComp.F90
  0: libMAPL.cap.so     00002AB637B7B3A1  mapl_capgridcompm         788  MAPL_CapGridComp.F90
```

**Comment by tclune** [comment] 2021-02-24 21:07
To be safe (re line numbers), which branch/version of MAPL?

**Comment by mathomp4** [comment] 2021-02-24 21:09
My guess is that line is a Memory print. I think I've seen it randomly before. It's like the `/proc/$PID` "file" is...wonky or something? and when we go to process it, our code finds something unexpected (text maybe?)

**Comment by tclune** [comment] 2021-02-24 21:11
For reference,  if this is develop, then the line is our `_RETURN` macro.    But it's a return that is supposed to issue ESMF_SUCCESS, and should not print anything.

**Comment by tclune** [comment] 2021-02-24 21:13
I must have the wrong version - line 1080 does not correspond to an executable line.

**Comment by rmontuoro** [comment] 2021-02-24 21:20
This is from branch `bugfix/rmontuoro/ufs` (revision cccff39) in fork `https://github.com/rmontuoro/MAPL`. This branch is up-to-date with `develop` and PR #721 & #722.

**Comment by tclune** [comment] 2021-02-24 21:59
ok - same lines in that version, so the stack trace is not very meaningful.   Is the crash reproducible?

**Comment by bena-nasa** [comment] 2021-03-08 18:01
I just noticed this when looking at the output when I was checking that develop as of now fixed all the other issues. This is reproducible. The last MAPL line in develop as of the time of this message is this:
```

         if( mapl_am_I_Root(this%vm) ) write(6,1000) AGCM_YY,AGCM_MM,AGCM_DD,AGCM_H,AGCM_M,AGCM_S,&
                                      LOOP_THROUGHPUT,INST_THROUGHPUT,RUN_THROUGHPUT,HRS_R,MIN_R,SEC_R,&
                                      mem_committed_percent,mem_used_percent
```

**Comment by rmontuoro** [comment] 2021-03-09 00:03
This issue is caused by `HRS_R` being negative, as `TIME_REMAINING ` becomes negative after the first time step. This is a consequence of setting `cap%nsteps = 1` when driving MAPL with an external clock: 
https://github.com/GEOS-ESM/MAPL/blob/deddd75edcf89e554cf1c3edeb47810dff1fd247/gridcomps/Cap/MAPL_CapGridComp.F90#L255-L258 to make sure MAPL will advance each component by one time step under the UFS.

Perhaps this issue could be resolved by using `TIME_REMAINING=max(0., TIME_REMAINING)`. Also, the diagnostic output could be made optional since it is not required for UFS-GOCART.

**Comment by bena-nasa** [comment] 2021-03-09 14:01
@rmontuoro @atrayano I agree that just making the throughput diagnostics optional is the simplest thing here. Either a resource parameter or just disable if the internal clock is detected, perhaps the latter?

**Comment by tclune** [comment] 2021-03-09 14:16
@rmontuoro We think that the "error" messages above in debugging are just exaggerated warnings about bad formats.   Others have observed that the run does not actually terminate.   We are investigating to see which specific edit descriptor(s) are actually the culprit.

**Comment by tclune** [comment] 2021-03-09 14:19
Ah the dangers of responding to the earliest email first.   I now see others are advocating a larger hammer.

**Comment by bena-nasa** [comment] 2021-03-09 14:23
There seem to be too bad descriptors when I examine the output:
```
  0:  AGCM Date: 2019/07/15  Time: 00:20:00  Throughput(days/day)[Avg Tot Run]:  116.8  116.8 3791.3  TimeRemaining(Est) 000:00:00   18.0% :  13.6% Mem Comm:Used
  0:  AGCM Date: 2019/07/15  Time: 00:40:00  Throughput(days/day)[Avg Tot Run]: ****** 5484.0 6518.1  TimeRemaining(Est) ***:59:59   18.3% :  14.4% Mem Comm:Used
```
The bad formatters correspond to the loop_throughput and HRS_R if you examine the write. As @rmontuoro has pointed out HRS_R depends on this time_remaining computation which will go negative because of the fact %nstep is 1 in the way UFS is using so what we are doing doesn't really make sense in the external clock context. 
I think the simplest thing for now is to just disable the throughput information if an external clock is passed.

**Closed** 2021-03-09 17:57 UTC
Labels: bug
