### ISSUE TITLE
what if  __GFORTRAN__  is defined 

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/MAPL#493] opened 2020-07-08 20:45 UTC
https://github.com/GEOS-ESM/MAPL/blob/9585c00fd79b388006585067fb07c5d67b311b14/base/MAPL_LocStreamMod.F90#L236-L258

What if __GFORTRAN__  is defined  and both tilelons and tilelats are present?  It ends up allocate a pointer twice. There are a handful of places like this in the subroutine.

**Comment by atrayano** [comment] 2020-07-08 20:56
Weiyuan, this is a workaround for a known gfortran bug. I am fairly much aware that this creates a memory leak, but at least the code runs. @mathomp4  had reported the issue to gcc developers couple of years ago (if I remember correctly, the latest gcc version back then was 6)

**Comment by weiyuan-jiang** [comment] 2020-07-09 15:50
I can confirm (at least from a simple test program) the gfortran 9.3.0 /home/mathomp4/GitG5Modules/SLES12/6.0.12/g5_modules.gcc9 fixes this "compiler internal error".  Should we remove those buggy stuff? @atrayano  @bena-nasa @tclune

**Comment by atrayano** [comment] 2020-07-09 16:01
@weiyuan-jiang, @mathomp4 has a reproducer. If he confirms tha gfortran 9.3.0 (and above) resolve the issue, it is totally fine to remove the workaround. My recollection is the this was not exhibiting "internal compiler error"

Alternatively, try to remove the #ifdefs and see you the code compiles, runs, and still produces zero-diff. Removing the #ifdef would only fix a memory leak, but should not affect the results

**Comment by atrayano** [comment] 2020-07-09 16:06
Even if the issues are fixed with 9.3.0, we might want to protect against older version of the compiler - for example, Harvard uses MAPL, and they compile with gfortran. I am not sure if they had transitioned to version 9

**Comment by tclune** [comment] 2020-07-09 17:15
First - I want to make certain that we actually have a reproducer.   @weiyuan-jiang did you demonstrate that the code fails with older gfortran (and the cleaner code)?   Simply not getting a internal compiler error is insufficient unless that was indeed the error that caused us to create the workaround.

Once we have a reproducer, we can then check which gfortran versions work and can  debate when to clean the code.   I like the idea of eliminating workarounds when they are no longer necessary, but it can be tricky to track them and act.

**Comment by weiyuan-jiang** [comment] 2020-07-09 17:25
This test program works fine in gfortran 9.3 but not in gfortran 6.5

module test_gfortran

   type s_data
      integer :: i
   end type

   type streamtype
      type(s_data), pointer :: s(:)=>null()
   end type

   type stream
     type (streamtype), pointer :: ptr=>null()
   end type
end module

program main
   use test_gfortran
   implicit none
   integer, pointer :: iptr(:)
   type(stream) :: tmp
   type(streamtype), pointer :: tmptype
   type(s_data), pointer :: s(:)

   allocate(s(5))
   s%i = 5
   allocate(tmptype)
   tmptype%s=>s
   tmp%ptr=> tmptype
   call get_pointer(tmp, iptr)
   print*, iptr

contains
   subroutine get_pointer(streamin, iptr)
      type(stream) :: streamin
      integer,pointer :: iptr(:)
      iptr => streamin%ptr%s%i
   end subroutine

end program



Error message for gfortran 6.5
 gfortran tmp.F90
tmp.F90:36:0:

       iptr => streamin%ptr%s%i
 
internal compiler error: Segmentation fault
0x5a58b8 ???
	../sysdeps/x86_64/start.S:118
Please submit a full bug report,
with preprocessed source if appropriate.

**Comment by mathomp4** [comment] 2020-07-09 17:27
I went back to [my Bugzilla report](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59093) and it looks like it was fixed in the 8 era. As I at some point in ESMA_cmake set the minimum GNU version to 8.3, I think we can say this workaround is now unneeded if we can show that.

**Comment by mathomp4** [comment] 2020-07-09 17:28
Note I tested that 6 and 7 on discover fail, 8 and 9 (and 10) work.

**Comment by mathomp4** [comment] 2020-07-09 17:30
> Weiyuan, this is a workaround for a known gfortran bug. I am fairly much aware that this creates a memory leak, but at least the code runs. @mathomp4 had reported the issue to gcc developers couple of years ago (if I remember correctly, the latest gcc version back then was 6)

Note. I reported this in GCC 4.3.0 so it was indeed a while back (2008!) and it was fixed in 2017. :)

**Comment by lizziel** [comment] 2020-07-09 21:18
I've been using gfortran 9.3 but it would be nice if we could support earlier versions to reduce the up front work for users. Do you plan on making compatibility with pre-9.3? If yes, what will be the earlier supported version? Which MAPL version will this update be in? I was planning on using 2.2.7 in the GCHP 13.0 release, but it sounds like I should update again.

**Comment by atrayano** [comment] 2020-07-09 21:57
@lizziel I would let @tclune and @mathomp4 decide on the build side. As far as fixing the issue, I am thinking modify the existing protection so that anything newer than 8 will not need nor use the protection (presumably the code will still run)
Something along these lines:
#define GCC_VERSION (__GNUC__ * 10000 \
                     + __GNUC_MINOR__ * 100 \
                     + __GNUC_PATCHLEVEL__)
…
/* Test for GCC > 8.2.0 */
#if GCC_VERSION < 80200

Of course, it needs additional logic to be triggered only for gfortran. I'll do this in the morning on a much fresher head

**Comment by mathomp4** [comment] 2020-07-10 12:51
> I've been using gfortran 9.3 but it would be nice if we could support earlier versions to reduce the up front work for users. Do you plan on making compatibility with pre-9.3? If yes, what will be the earlier supported version? Which MAPL version will this update be in? I was planning on using 2.2.7 in the GCHP 13.0 release, but it sounds like I should update again.

@lizziel I suppose technically as it is, we allow 8.3 and higher in `GNU.cmake`. I'm honestly not sure if even that works, but I think it still does? Some of @tclune 's more exciting OO stuff means we do need to keep close to current with GNU.

Frankly, I think we probably need to advance our required Intel version. I think we still only require 15.1 and my guess is we need to have at least 18.something there.

**Comment by tclune** [comment] 2020-07-10 14:13
@atrayano I'm not sure that putting in the guard logic to leave the workaround in place  for the older compilers is useful.   Yes we'd eliminate the small memory leak for the newer versions of the compiler, but the ugly kludge just got uglier.

_If_ MAPL (with GFE, etc) still works with GFortran 7.x, then we should just leave the workaround in place for now.   But, I think my previous discussions with Lizzie showed that at least some parts of yaFyaml require at least 8.x, in which case the kludge may as well be removed.

@lizziel Please let us know if you really think you can still use GFortran 7.x with the latest MAPL.

**Comment by lizziel** [comment] 2020-07-10 14:37
@tclune , ideally we would be able to use 8.3+ and ifort18+ which are the minimum versions I have been telling people. If 8.2 also worked that would be excellent since I have libraries built with that version ready to go to test with. A few weeks ago I tested with 8.2 and it failed, and I can see if I still have my log for that if that is helpful. 

Regarding Intel, I have run into issues with ifort17. I can report what those are if you would find that helpful, but I don't really see a need to go back that far.

If the model runs with 8.x but there is a memory leak, could you quantify that issue further if it will not be fixed? Or even better, is there a central location on GitHub that lists all of the compiler/MPI versions tested along with results and notes?

**Comment by tclune** [comment] 2020-07-10 15:17
I think that 8.3 should work.  And am willing to spend some effort to make that happen if it is close.   The one bit that makes me nervous is yaFyaml.

I don't think you should worry about this particular memory leak.  AFAIK, GCHP does not use LocStream.    

In any event, since it sounds like there is not a use case for getting 7.3 to work (too much effort, too little gain), we can eliminate this leak.

**Comment by mathomp4** [comment] 2021-02-22 14:32
@tclune Was the GCC 8.3 issue taken care of in this? Or maybe the "intentional leak" was removed?

**Comment by tclune** [comment] 2021-02-22 19:47
I'm terribly confused after reading the thread.    If the "intentional leak" was removed, it was not by me.

MAPL requires at least 8 and 8 supposedly has the fix.  So the leak should be removed (if it has not already) and this ticket should be closed.

**Comment by mathomp4** [comment] 2021-03-08 19:33
Closing this as I think we got it sort of working with #735

**Closed by mathomp4** 2021-03-08 19:33 UTC
